<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net6.0;net9.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>

    <!-- NuGet Package Properties -->
    <PackageId>GuidPlus</PackageId>
    <Authors>BaerMitUmlaut</Authors>
    <Company>GuidPlus</Company>
    <Copyright>Copyright © BaerMitUmlaut 2022</Copyright>
    <Description>
      GUID+ is a drop-in replacement for .NET's default UUID generation, enabling generation of version 6, 7 and 8 UUIDs.
    </Description>
    <PackageIcon>package-icon.png</PackageIcon>
    <PackageTags>uuid guid</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/BaerMitUmlaut/GuidPlus</PackageProjectUrl>
    <RepositoryUrl>https://github.com/BaerMitUmlaut/GuidPlus.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\package-icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.1.1" PrivateAssets="All" />
    <PackageReference Include="MinVer" Version="3.0.0" PrivateAssets="All" />
  </ItemGroup>
  
  <Choose>
    <When Condition="'$(TargetFramework)' == 'netstandard2.0' or '$(TargetFramework)' == 'netstandard2.1'">
      <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Primitives" Version="9.0.0" />
      </ItemGroup>
    </When>
  </Choose>

  <Choose>
    <When Condition="'$(TargetFramework)' == 'net9.0'">
      <ItemGroup>
        <Using Alias="LockClass" Include="System.Threading.Lock"/>
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <Using Alias="LockClass" Include="System.Object"/>
      </ItemGroup>
    </Otherwise>
  </Choose>

  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>GuidPlus.Test</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
  
  <ItemGroup>
    <Using Include="$(RootNamespace).Internal"/>
  </ItemGroup>

</Project>
